### ISSUE TITLE
The dev set is init by the test set?

### ISSUE THREAD

**Issue by CheaSim** [thunlp/PTR#2]
https://github.com/thunlp/PTR/blob/7cce6f124ce99518d8d1e6a8efb2271de7edbf73/code_script/run_prompt.py#L149

I found that the val_dataset is actually the test dataset.

**Comment by THUCSTHanxu13** [comment]
If you want to use the dev set to select the best checkpoint, you can set name="val".

**Comment by THUCSTHanxu13** [comment]
In this code, the same code can work for both dev and test set.

**Comment by jzhang38** [comment]
@THUCSTHanxu13  May I ask the score reported in the paper is obtained by selecting from the dev set or test set?

**Comment by THUCSTHanxu13** [comment]
For few-shot settings, the scores reported in the paper is obtained by selecting from the dev set. For full-set settings, the scores reported in the paper is obtained by the performance of the last checkpoint on the dev set.
