### ISSUE TITLE
some questions about paper

### ISSUE THREAD

**Issue by wjczf123** [thunlp/PTR#3]
Hi Xu,
I have some questions about this paper. And i am looking forward to your reply.
1. I notice that this paper focuses on relation extraction (a classification problem). Thus, why entity classification task is needed (e.g. equation (1))?
2. I also notice that you use REVERSED operation to reverse a part of relations. What is the standard for REVERSED?
3. I also notice that ENTITY MARKER also use REVERSED operation. How do they combine? Exchange the position of [E1] and [E2]?
4. There is also an implementation detail issue (common problem about prompt-based learning). How many [MASK] do we need in equation (3)? Does this require the same number of tokens in the label words (label words in Equation 4)? E.g., all words in V_{[MASK]_1} have 2 tokens after BPE?

**Comment by wjczf123** [comment]
Another question is temp_dd is needed in run_large_semeval.sh.
But there is only temp.txt.
I'm not sure if they (i.e., temp.txt and temp_dd.txt) are the same.

**Comment by wjczf123** [comment]
Looking forward to hearing from you.

**Comment by THUCSTHanxu13** [comment]
temp.txt is used for experiments. We have fixed this bug in the script.

**Comment by wjczf123** [comment]
Can you answer other questions? Thanks!

**Comment by THUCSTHanxu13** [comment]
For your questions:

1. On the one hand, it is difficult to design appropriate label words for prompts without considering entity information. On the other hand, implicitly considering entity information is also a good way to introduce prior information, which is also beneficial to the task.

2. For example, in the 'REVERSED' setting, we extract (e2, 'per:origin'^-1, e1) instead of (e1, 'per:origin', e2).

3. For Entity Marker, we exchange the positions of those special entity markers.

4. The number of [MASK] depends on your prompt design. We suggest that all classes have the same number of masking tokens.

**Comment by wjczf123** [comment]
Thank you very much for your reply. 
For the second question (I also notice that you use REVERSED operation to reverse a part of relations. What is the standard for REVERSED?), I notice that you write 'Hence, in our experiments, we apply two settings for PTR, one is to build prompts without changing any relations, and the other is to build prompts after reversing a part of relations.' in paper.
My confusion is that REVERSED is used for a part of relations, not all relations.
How to determine whether a relation is operated with REVERSED?

**Comment by THUCSTHanxu13** [comment]
HaHaHa~ it is an interesting question. Whether we reverse one relation depends on whether it is easy to write its prompt template. In fact, we mainly reverse the relation ''per:origin''.

**Comment by wjczf123** [comment]
OK. Thank you a lot.

**Comment by THUCSTHanxu13** [comment]
We believe that an advantage of reversing relations is that we can distinguish some similar relations, such as "per:countries_of_residence" and "per:origin". 

Intuitively, by reversing 'per:origin', 'per:origin^-1' can be the relation between country and person, different from 'per:countries_of_residence' indicating the relation between person and country.

We think this setting is reasonable in practice, but it should not be compared with the conventional setting.

**Comment by wjczf123** [comment]
Thank you a lot. This is very intuitive.

**Comment by wjczf123** [comment]
Thank you a lot. This is very intuitive.

**Comment by jzhang38** [comment]
@THUCSTHanxu13  Hi Han Xu, may I ask in which part of the code did you implement the reverse operation. It seems to me that the code does not use reverse. Thank you！
