### ISSUE TITLE
有个疑问，关于fine tuning

### ISSUE THREAD

**Issue by znsoftm** [thunlp/PTR#8]
用中文可以充分表达，恕用中文提问。

看到论文中提到本文的优势是不用fine tuning, 但是在model中，其实是分两条线进行tuning的，对bertmodel本身，和对另一个映射网络。以我初浅的理解，它应该还是算fine tuning, 一般叫prompt tuning, 对否？

我理解的，如果不用tuing, 应该只是用bertmodel本身的查询 或隐层输出 表示而不能去反向调整bertmodel , 但是代码实际上做了这个工作。
请明示。

**Comment by THUCSTHanxu13** [comment]
其实这个文章里面的prompt tuning应该是prompt-oriented fine-tuning，相当于引入了prompt来构造分类任务，模型全参数还是需要调整的。google的soft prompt工作出来后，prompt tuning现在更多的指只微调prompt，预训练模型参数不变。

这里面叫prompt tuning有点历史原因，这个文章出来的比较早，细分的比较粗糙
