### ISSUE TITLE
关于使用bert模型

### ISSUE THREAD

**Issue by ZihaoZheng98** [thunlp/PTR#9]
哈喽，我在跑bert模型时出现了assert错误，看样子是 's在编码的时候bert将‘s拆分成'和s？代码中好像不能解决这个问题？

**Comment by THUCSTHanxu13** [comment]
这是bert字表的问题，我们用的roberta的模型，bert的话's比较麻烦

**Comment by ZihaoZheng98** [comment]
还有个问题，论文中写的是使用各个mask位置logits的乘积作为最终关系的logits，但是看代码evaluate部分好像是直接相加？相加是否合适呢？

**Comment by THUCSTHanxu13** [comment]
好问题，其实是两个loss，一个是各部分预测loss，这个不用多讲。相加之后算概率，和概率连乘数学上是等价的，同学可以自己写一下式子展开，就看出来了。

**Comment by suexin27** [comment]
您好，请问 AssertionError 您解决了吗？
